@file:Suppress("unused")
package ru.cashbox.android.common

const val APP_NAME = "Cashbox"
const val PACKAGE = "cashbox.android"
const val DATABASE_NAME = "database_cashbox"
const val BASE_API_ADDRESS = "https://%s.inactivesearch.ru/_api/cashbox/"
const val IMG_PATH = "img/"
const val DEFAULT_PRINTER_PORT = "5555"

const val CURRENT_ID_TERMINAL = "currentIdTerminal"
const val CURRENT_ID_EMPLOYEE = "currentIdEmployee"
const val CURRENT_ID_CASHSESSION = "currentIdCashsession"

const val UNDEFINED_ID = -1L

const val INTERNET_ERROR = 12053
const val ARGS_ERROR = 12054

const val ACCOUNT_ID = "accountId"
const val API = "api"
const val CASH_BALANCE = "cashBalance"
const val CASHSESSION_TYPE = "cashsessionType"
const val CASHSESSIONS = "cashsessions"
const val CATEGORIES = "categories"
const val CLOSED = "closed"
const val CODE = "code"
const val COMMENT = "comment"
const val COST_PRICE = "costPrice"
const val COUNT = "count"
const val DATE = "date"
const val DISCOUNT = "discount"
const val DOMAIN = "domain"
const val INGREDIENTS = "ingredients"
const val ITEM_ID = "itemId"
const val ITEM_TIMESTAMP = "itemTimestamp"
const val ITEMS = "items"
const val LOGOUT_ALL = "logoutAll"
const val MESSAGE = "message"
const val MODIFICATOR_ID = "modificatorId"
const val MODIFICATORS = "modificators"
const val OPENED = "opened"
const val PAYED_TYPE = "payedType"
const val PASSWORD = "password"
const val PIN = "pin"
const val PRICE = "price"
const val RECORDS = "records"
const val REMEMBER_ME = "rememberMe"
const val SESSIONS = "sessions"
const val SESSIONS_TERMINAL = "sessionsTerminal"
const val SESSIONS_EMPLOYEE = "sessionsEmployee"
const val STATUS = "status"
const val SUM = "sum"
const val TECH_MAPS = "techMaps"
const val TECHMAPS = "techmaps"
const val TECHMAP_ID = "techmapId"
const val TEXT = "text"
const val TOKEN = "token"
const val TOKEN_EMPLOYEE = "tokenEmployee"
const val TOKEN_TERMINAL = "tokenTerminal"
const val TYPE = "type"
const val USERNAME = "username"
const val USERS = "users"
const val VENDOR_ID = "vendorId"